### ISSUE TITLE
Performance report data is strange

### ISSUE THREAD

**Issue by SeyfSV** [ibm-messaging/mqperf#2]
Hi  @stmassey and @pharrishur, 
I looked performance reports for MQ 9.1 for Linux and Windows.
Can you explain why rows from 2 to 4 show the same data for both OSs in some coresponding tables? For example tables 3 and 4
Linux:
![image](https://user-images.githubusercontent.com/25712100/73259160-379d0480-41d8-11ea-9620-b53e9f8cab52.png)

![image](https://user-images.githubusercontent.com/25712100/73258927-be9dad00-41d7-11ea-8705-d6741252a49b.png)

Windows:
![image](https://user-images.githubusercontent.com/25712100/73259184-41266c80-41d8-11ea-9c33-fa9b24e01c61.png)

![image](https://user-images.githubusercontent.com/25712100/73258889-b2b1eb00-41d7-11ea-83d4-e9c36328bfd7.png)

**Comment by stmassey** [comment]
Hi - thanks for reporting the issue. It looks like weve had an issue in our graph generation. Ive updated the data in the Windows report and incremented the version to 1.1.
