### ISSUE TITLE
mqperf

### ISSUE THREAD

**Issue by brandelik** [ibm-messaging/mqperf#3]
All references to developerworks techarticles need to be checked and actualized.
They point nowhere now that the great relocation has dropped them.
See https://github.com/ibm-messaging/mqperf/blob/gh-pages/MQ_Performance_Best_Practices_v1.0.pdf

**Comment by pharrishur** [comment]
Thank you for bringing those broken links to our attention. I've fixed the doc in a new version (V1.0.1). I appreciate the frustration this can cause.
